# Ordinal Encoding

In [71]:
from numpy import array

In [72]:
from sklearn.preprocessing import OrdinalEncoder

In [73]:
data = array([['red'],['green'],['black'],['blue']])

In [74]:
data.dtype

dtype('<U5')

In [75]:
encoder = OrdinalEncoder()

In [76]:
enc_data = encoder.fit_transform(data)

In [77]:
enc_data

array([[3.],
       [2.],
       [0.],
       [1.]])

In [78]:
from sklearn.preprocessing import LabelEncoder

In [79]:
LE = LabelEncoder()

In [80]:
LE_data = LE.fit_transform(data)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


In [81]:
data

array([['red'],
       ['green'],
       ['black'],
       ['blue']], dtype='<U5')

# OneHotEncoding

In [82]:
from sklearn.preprocessing import OneHotEncoder

In [83]:
OHE = OneHotEncoder(sparse=False)

In [84]:
OHE_data= OHE.fit_transform(enc_data)

In [85]:
OHE_data

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [86]:
# sparse matrix : contains only zero and 1's
print(OHE_data)

[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


# Remove Dummy Veriable Trap

In [87]:
OHE_data = OHE_data[:,:3]

In [88]:
OHE_data

array([[0., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

# OneHotEncoding On Label Encoded data

In [89]:
OHE_LE = OneHotEncoder()

In [90]:
OHE_LE_data = OHE_LE.fit_transform(data)

In [91]:
OHE_LE_data

<4x4 sparse matrix of type '<class 'numpy.float64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [93]:
OHE_LE_data.toarray()[:,:3]

array([[0., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])